### PR TITLE
Sinan branch

### PR DESCRIPTION
**Pull request by sinancengiz**
role column and admin link added to tables and db:seed file updated according to models

### CODE REVIEW

**Comment by DeeTheDev** [comment]
@sinancengiz I'm curious, why did you create a "Stuff" model?

**Comment by sinancengiz** [comment]
Hey @DeeTheDev To put stuff In it . We have students, mentors and stuff

**Comment by DeeTheDev** [comment]
@sinancengiz Makes more sense now!

**Comment by sinancengiz** [comment]
Hey guys sorry for the typo I changed the stuff to staff and updated the code . Please review the changes an  let me know if there is something to fix

**Comment by andresochoa91** [comment]
Great Sinan, thank you!!!

**Pull request merged**
